@echo off
color b
title Science Trivia
echo.
echo -----------------
echo.
echo.
echo Welcome to science Trivia
echo.
echo.
echo -----------------
echo.
echo Using symbols or the alphabet as well as all numbers except 1,2 and 3 is not allowed. 
pause
cls
goto 1
:1
echo What does valence mean?
echo 1 Outer
echo 2 Inner
echo 3 Middle
set/p Science Trivia=Choose an answer.
if%Science Trivia%==1 goto Correct
if %Science Trivia%==2 goto incorrect
if %Science Trivia%==3 goto incorrect
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 2
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto continued
:continued
cls
:2
echo What is buzzing around inside and outside the atom?
echo 1 Protons
echo 2 Electrons
echo 3 Rupees
set/p Science Trivia=Choose an answer.
if %Science Trivia%==1 goto incorrect
if%Science Trivia%==2 goto Correct
if %Science Trivia%==3 goto incorrect
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 3
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end 
cls
:3
echo What is the nucleus of an atom made of?
echo 1 Protons and neutrons
echo 2 Electrons and protons
echo 3 Cells
set/p Science Trivia=Choose an answer.
if%Science Trivia%==1 goto Correct
if %Science Trivia%==2 goto incorrect
if %Science Trivia%==3 goto incorrect
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 4
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end
cls
:4
echo What is the definition of Element?
echo 1 Something to do with nature (fire, water).
echo 2 Something represented on the periodic table of elements.
echo 3 A materia mmade out of only one types of atom.
set/p Science Trivia=Choose an answer.
if %Science Trivia%==1 goto incorrect
if%Science Trivia%==2 goto Correct
if%Science Trivia%==3 goto Correct
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 5
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end
cls
:5
echo What is an example of phisical change?
echo 1 Wood burning.
echo 2 Metal rusting.
echo 3 A rock being crushed.
set/p Science Trivia=Choose an answer.
if %Science Trivia%==1 goto incorrect
if %Science Trivia%==2 goto incorrect
if%Science Trivia%==3 goto Correct
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 6
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end
cls
:6
echo What is an example of chemical change?
echo 1 Aluminum foil being crumpled and smoothed.
echo 2 Cookies being baked.
echo 3 Water condensing.
set/p Science Trivia=Choose an answer.
if %Science Trivia%==1 goto incorrect
if%Science Trivia%==2 goto Correct
if %Science Trivia%==3 goto incorrect
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 7
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end
cls
:7
echo What does state mean?
echo 1 The form matter is in.
echo 2 A part of a country.
echo 3 The condition of a person or thing.
set/p Science Trivia=Choose an answer.
if%Science Trivia%==1 goto Correct
if %Science Trivia%==2 goto incorrect
if %Science Trivia%==3 goto incorrect
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 8
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end
cls
:8
echo What is the definition of mass?
echo 1 The amount of matter in something.
echo 2 The amount of space something takes up.
echo 3 The thing that makes up everything.
set/p Science Trivia=Choose an answer.
if%Science Trivia%==1 goto Correct
if %Science Trivia%==2 goto incorrect
if %Science Trivia%==3 goto incorrect
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 9
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end
cls
:9
echo All mater is made up of.
echo 1 Moecules
echo 2 Cells
echo 3 Atoms
set/p Science Trivia=Choose an answer.
if %Science Trivia%==1 goto incorrect
if %Science Trivia%==2 goto incorrect
if%Science Trivia%==3 goto Correct
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 10
goto continued 
:incorrect
cls
echo Wrong answer.
pause
goto end
:end 
cls
:10
echo What is salt made of?
echo 1 Salt is an element and is found naturally
echo 2 I dont know?
echo 3 Sodium and Chlorine
set/p Science Trivia=Choose an answer.
if %Science Trivia%==1 goto incorrect
if %Science Trivia%==2 goto incorrect
if%Science Trivia%==3 goto Correct
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
pause
cls
goto 11
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto end
:end
cls
:12
echo What is water an exmple of?
echo 1 An element.
echo 2 A compund.
echo 3 A mixture.
set/p Science Trivia=Choose an answer.
if %Science Trivia%==1 goto incorrect
if%Science Trivia%==2 goto Correct
if %Science Trivia%==3 goto incorrect
if %Science Trivia%==123 goto incorrect
if %Science Trivia%==12 goto incorrect
if %Science Trivia%==321 goto incorrect
if %Science Trivia%==32 goto incorrect
if %Science Trivia%==a goto incorrect
if %Science Trivia%==b goto incorrect
if %Science Trivia%==c goto incorrect
if %Science Trivia%==d goto incorrect
if %Science Trivia%==e goto incorrect
if %Science Trivia%==f goto incorrect
if %Science Trivia%==g goto incorrect
if %Science Trivia%==h goto incorrect
if %Science Trivia%==i goto incorrect
if %Science Trivia%==j goto incorrect
if %Science Trivia%==k goto incorrect
if %Science Trivia%==l goto incorrect
if %Science Trivia%==m goto incorrect
if %Science Trivia%==n goto incorrect
if %Science Trivia%==o goto incorrect
if %Science Trivia%==p goto incorrect
if %Science Trivia%==q goto incorrect
if %Science Trivia%==r goto incorrect
if %Science Trivia%==s goto incorrect
if %Science Trivia%==t goto incorrect
if %Science Trivia%==u goto incorrect
if %Science Trivia%==v goto incorrect
if %Science Trivia%==w goto incorrect
if %Science Trivia%==x goto incorrect
if %Science Trivia%==y goto incorrect
if %Science Trivia%==z goto incorrect
if %Science Trivia%==A goto incorrect
if %Science Trivia%==B goto incorrect
if %Science Trivia%==C goto incorrect
if %Science Trivia%==D goto incorrect
if %Science Trivia%==E goto incorrect
if %Science Trivia%==F goto incorrect
if %Science Trivia%==G goto incorrect
if %Science Trivia%==H goto incorrect
if %Science Trivia%==I goto incorrect
if %Science Trivia%==J goto incorrect
if %Science Trivia%==K goto incorrect
if %Science Trivia%==L goto incorrect
if %Science Trivia%==M goto incorrect
if %Science Trivia%==N goto incorrect
if %Science Trivia%==O goto incorrect
if %Science Trivia%==P goto incorrect
if %Science Trivia%==Q goto incorrect
if %Science Trivia%==R goto incorrect
if %Science Trivia%==S goto incorrect
if %Science Trivia%==T goto incorrect
if %Science Trivia%==U goto incorrect
if %Science Trivia%==V goto incorrect
if %Science Trivia%==W goto incorrect
if %Science Trivia%==X goto incorrect
if %Science Trivia%==Y goto incorrect
if %Science Trivia%==Z goto incorrect
if %Science Trivia%==4 goto incorrect
if %Science Trivia%==5 goto incorrect
if %Science Trivia%==6 goto incorrect
if %Science Trivia%==7 goto incorrect
if %Science Trivia%==8 goto incorrect
if %Science Trivia%==9 goto incorrect
if %Science Trivia%==0 goto incorrect
:Correct
cls
echo CORRECT ANSWER!!!
goto finish
goto continued
:incorrect
cls
echo Wrong answer.
pause
goto finish
:finish
echo.
echo.
echo -------------------------------------------
echo.
echo.
echo Congradulations you have completed science trivia!!!
echo.
echo.
echo -------------------------------------------
echo.
echo.
pause
echo